version: '1'
services:
  telegram-notif-container:
    image: telegram-notif
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "python3 -u notifier.py"
    links:
      - redis_db
  redis_db:
    image: redis:latest